### ISSUE TITLE
Rendering Footnotes

### ISSUE THREAD

**Issue by stoweboyd** [mcndt/noteshare.space#24]
It would be good if footnotes were rendered in the copied file.

In my use case, I write comments and place tags and other annotations in footnotes, but for sharing with others those would be better at the foot of the rendered file.

**Comment by mcndt** [comment]
for future reference, a good starting point: https://github.com/markedjs/marked/issues/1562#issuecomment-551269829

**Comment by mcndt** [comment]
Works now!

**Comment by stoweboyd** [comment]
Doesn't seem to work in all cases:

![Screen Shot 2022-08-23 at 4 49 55 PM](https://user-images.githubusercontent.com/3037422/186262976-85e9334c-538f-485a-b589-8549bddc69ea.png)

**Comment by mcndt** [comment]
So sorry for my late response, I have been traveling.

I am unfamiliar with this footnote syntax. Is it a way to define the footnote text inline? I was previously only familiar with this syntax:

```md
This is a paragraph^[1].

[1]: This is the footnote text, which will be rendered at the bottom of the page.
```

**Comment by stoweboyd** [comment]
Yes, it is an inline footnote. Like^[this is a footnote] which shows at the
foot of the rendered file with an ordinal and the text. See
https://help.obsidian.md/How+to/Format+your+notes

You can also use inline footnotes. ^[notice that the carat goes outside of
the brackets on this one.]

**Comment by mcndt** [comment]
I created a new issue to track this bug separately, see #31.

**Comment by stoweboyd** [comment]
Still doesn't seem to be working?

**Comment by mcndt** [comment]
As I said, I created a new issue to track the bug. I haven't fixed it just yet :) But don't worry, it's on my radar. 

You can subscribe to the new thread to follow progress: #31

**Comment by stoweboyd** [comment]
Aha!
