### ISSUE TITLE
[Feature request] Transparency of ops expenses

### ISSUE THREAD

**Issue by elight** [mcndt/noteshare.space#32]
This is a lovely idea. It is very generous of you to offer it freely to the community!

Would you be willing to write a small doc describing the monetary and personal costs of operating this service?

As a dev, I'm well aware that there's often a lot more that goes into a service than just writing it and deploying a docker image. Not asking for humble brags: just for you to get the recognition and, ideally, deserves community support.

Cheers!

**Comment by mcndt** [comment]
Hi Evan,

It's a good idea to have some dedicated writing about this on the website and the GitHub repo. I have been open about this on Discord but that's pretty hard to find.

Basically, I architected the serverside code to be as light and portable as possible. Currently, it runs on a VPS I rent for about 7$/month. I already rented this VPS for other purposes, so I haven no problem paying out of pocket for hosting.

Once I enable encrypting embedded images, the storage costs will increase and I may turn towards community funding, or a tiered system. But you can rest assured that the current functionality will remain online indefinitely.

**Comment by mcndt** [comment]
Post is live: https://noteshare.space/funding
