### ISSUE TITLE
[Bug] Shorthand strikethrough markdown not displayed properly

### ISSUE THREAD

**Issue by derekantrican** [mcndt/noteshare.space#36]
**Describe the bug**

Obsidian allows for a "shorter" strikethrough format where `~~` is only needed at the beginning of a line to strikethrough the entire line. noteshare.space does not seem to support this

**To Reproduce**

Create & share a note with the following text:

`~~This is a test`

**Expected behavior**

In Obsidian, this produces:

~~This is a test~~

**Screenshots**

Screenshot comparing Obsidian vs noteshare.space:

![image](https://user-images.githubusercontent.com/1558019/201990505-1e378c7d-2374-42f8-8743-a04b94ea9f66.png)

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Brave (latest)
 - Obsidian Version: 1.0.3

**Comment by mcndt** [comment]
Hey! I believe this is unintended behavior on Obsidian's part. This shorthand is not rendered in reader mode:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/23149353/202222420-cd8f9525-afa7-49f0-b826-99e4e72f9f32.png">
